language: ruby
sudo: false
before_install: gem install bundler
matrix:
  allow_failures:
    - rvm: jruby-head
  fast_finish: true
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.1.9.2-
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.0
      gemfile: Gemfile
    - rvm: 2.1.1
      gemfile: Gemfile
    - rvm: 2.2.0
      gemfile: Gemfile
      env: COVERAGE=true
    - rvm: jruby-18mode
      gemfile: gemfiles/Gemfile.1.9.2-
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: jruby-head
      gemfile: Gemfile
notifications:
  email: false

